<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reply.proto

namespace Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>messages.Reply</code>
 */
class Reply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 task_id = 1;</code>
     */
    protected $task_id = 0;
    /**
     * Generated from protobuf field <code>uint32 status = 2;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>bytes response = 3;</code>
     */
    protected $response = '';
    /**
     * Generated from protobuf field <code>bytes context = 4;</code>
     */
    protected $context = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $task_id
     *     @type int $status
     *     @type string $response
     *     @type string $context
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Reply::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 task_id = 1;</code>
     * @return int
     */
    public function getTaskId()
    {
        return $this->task_id;
    }

    /**
     * Generated from protobuf field <code>uint32 task_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkUint32($var);
        $this->task_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 status = 2;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>uint32 status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkUint32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes response = 3;</code>
     * @return string
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Generated from protobuf field <code>bytes response = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkString($var, False);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes context = 4;</code>
     * @return string
     */
    public function getContext()
    {
        return $this->context;
    }

    /**
     * Generated from protobuf field <code>bytes context = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setContext($var)
    {
        GPBUtil::checkString($var, False);
        $this->context = $var;

        return $this;
    }

}

