<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>messages.Task</code>
 */
class Task extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 task_id = 1;</code>
     */
    protected $task_id = 0;
    /**
     * Generated from protobuf field <code>bytes task = 2;</code>
     */
    protected $task = '';
    /**
     * Generated from protobuf field <code>bytes context = 3;</code>
     */
    protected $context = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $task_id
     *     @type string $task
     *     @type string $context
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Task::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 task_id = 1;</code>
     * @return int
     */
    public function getTaskId()
    {
        return $this->task_id;
    }

    /**
     * Generated from protobuf field <code>uint32 task_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkUint32($var);
        $this->task_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes task = 2;</code>
     * @return string
     */
    public function getTask()
    {
        return $this->task;
    }

    /**
     * Generated from protobuf field <code>bytes task = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTask($var)
    {
        GPBUtil::checkString($var, False);
        $this->task = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes context = 3;</code>
     * @return string
     */
    public function getContext()
    {
        return $this->context;
    }

    /**
     * Generated from protobuf field <code>bytes context = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setContext($var)
    {
        GPBUtil::checkString($var, False);
        $this->context = $var;

        return $this;
    }

}

