<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reply.proto

namespace GPBMetadata;

class Reply
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
l
reply.protomessages"K
Reply
task_id (
status (
response (
context (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

