<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace GPBMetadata;

class Task
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
V

task.protomessages"6
Task
task_id (
task (
context (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

